# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [4]:
print(np.__version__)

2.2.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
import numpy as np

a = np.random.rand(2, 3, 5)
print("Method 1:", a)

a = np.random.random((2, 3, 5))
print("Method 2:", a)

a = np.random.random_sample((2, 3, 5))
print("Method 3:", a)

a = np.random.uniform(0, 1, (2, 3, 5))
print("Method 4:", a)

a = np.random.randn(2, 3, 5)
print("Method 5:", a)


Method 1: [[[0.84457135 0.24596875 0.58850156 0.01983009 0.12284487]
  [0.84225521 0.43351503 0.33450696 0.06833435 0.16860517]
  [0.41615158 0.97657004 0.20880316 0.28000742 0.41010462]]

 [[0.2364441  0.5333964  0.50365711 0.19989447 0.3190449 ]
  [0.40523009 0.88042144 0.61570968 0.20597535 0.0977425 ]
  [0.02711601 0.58079171 0.00789004 0.04381054 0.18636474]]]
Method 2: [[[0.20242069 0.55012637 0.44483709 0.7917133  0.94730237]
  [0.70495039 0.40877166 0.08635359 0.05042327 0.53336357]
  [0.18481405 0.40735118 0.48357674 0.42849859 0.92795162]]

 [[0.62057485 0.36079327 0.91972044 0.19143477 0.11254638]
  [0.34517015 0.24751309 0.865399   0.76319769 0.27274847]
  [0.99679013 0.09508508 0.75736692 0.84186059 0.67704855]]]
Method 3: [[[0.66106367 0.36212665 0.58036136 0.95558758 0.75197873]
  [0.29109645 0.07562074 0.66867916 0.85267841 0.2241037 ]
  [0.97833137 0.7322102  0.32256542 0.99520812 0.4551873 ]]

 [[0.33668508 0.60477317 0.18187735 0.09558085 0.28135438]
  [0.62391654 0.


### 4. Print a.


In [6]:
print("Method 5:", a)


Method 5: [[[ 1.2116421   0.43129874 -0.60776219 -0.15106913  1.41528744]
  [-0.05361008 -1.94444541  0.46646333  0.2486735   0.79732401]
  [-1.23001069  0.99802567  1.49307161  0.80018949  0.59417603]]

 [[ 0.29835715 -0.31766173  0.71073945  1.20933111  0.19207981]
  [ 0.92167189  0.81391779 -0.19201672  1.92437809 -0.87213041]
  [-0.69819989  0.91668369 -0.76191589 -1.66342146 -0.19399098]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [ ]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
print("Same size:", a.size == b.size)

Same size: True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
#Their shapes are different, means its not possible.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [14]:
c = b.transpose(1, 2, 0)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [15]:
d = c + a
print(d)

[[[ 2.2116421   1.43129874  0.39223781  0.84893087  2.41528744]
  [ 0.94638992 -0.94444541  1.46646333  1.2486735   1.79732401]
  [-0.23001069  1.99802567  2.49307161  1.80018949  1.59417603]]

 [[ 1.29835715  0.68233827  1.71073945  2.20933111  1.19207981]
  [ 1.92167189  1.81391779  0.80798328  2.92437809  0.12786959]
  [ 0.30180011  1.91668369  0.23808411 -0.66342146  0.80600902]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print("a", a)
print("d", d)

# The arrays structure from a matches the structure from d, so Numpy can do the addition.


a [[[ 1.2116421   0.43129874 -0.60776219 -0.15106913  1.41528744]
  [-0.05361008 -1.94444541  0.46646333  0.2486735   0.79732401]
  [-1.23001069  0.99802567  1.49307161  0.80018949  0.59417603]]

 [[ 0.29835715 -0.31766173  0.71073945  1.20933111  0.19207981]
  [ 0.92167189  0.81391779 -0.19201672  1.92437809 -0.87213041]
  [-0.69819989  0.91668369 -0.76191589 -1.66342146 -0.19399098]]]
d [[[ 2.2116421   1.43129874  0.39223781  0.84893087  2.41528744]
  [ 0.94638992 -0.94444541  1.46646333  1.2486735   1.79732401]
  [-0.23001069  1.99802567  2.49307161  1.80018949  1.59417603]]

 [[ 1.29835715  0.68233827  1.71073945  2.20933111  1.19207981]
  [ 1.92167189  1.81391779  0.80798328  2.92437809  0.12786959]
  [ 0.30180011  1.91668369  0.23808411 -0.66342146  0.80600902]]]



### 12. Multiply a and c. Assign the result to e.


In [21]:
e = a * c
print(e)

[[[ 1.2116421   0.43129874 -0.60776219 -0.15106913  1.41528744]
  [-0.05361008 -1.94444541  0.46646333  0.2486735   0.79732401]
  [-1.23001069  0.99802567  1.49307161  0.80018949  0.59417603]]

 [[ 0.29835715 -0.31766173  0.71073945  1.20933111  0.19207981]
  [ 0.92167189  0.81391779 -0.19201672  1.92437809 -0.87213041]
  [-0.69819989  0.91668369 -0.76191589 -1.66342146 -0.19399098]]]




### 13. Does e equal to a? Why or why not?


In [23]:
print(e == a)

#They match because we multiply every number by 1. Means they stay unchanged.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [26]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [28]:
f = np.empty((2,3,5))
print(f)

[[[1.2116421  0.43129874 0.60776219 0.15106913 1.41528744]
  [0.05361008 1.94444541 0.46646333 0.2486735  0.79732401]
  [1.23001069 0.99802567 1.49307161 0.80018949 0.59417603]]

 [[0.29835715 0.31766173 0.71073945 1.20933111 0.19207981]
  [0.92167189 0.81391779 0.19201672 1.92437809 0.87213041]
  [0.69819989 0.91668369 0.76191589 1.66342146 0.19399098]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            val = d[i, j, k]
            if val == d_min:
                f[i, j, k] = 0
            elif val == d_max:
                f[i, j, k] = 100
            elif val == d_mean:
                f[i, j, k] = 50
            elif d_min < val < d_mean:
                f[i, j, k] = 25
            elif d_mean < val < d_max:
                f[i, j, k] = 75


d:
[[[ 2.2116421   1.43129874  0.39223781  0.84893087  2.41528744]
  [ 0.94638992 -0.94444541  1.46646333  1.2486735   1.79732401]
  [-0.23001069  1.99802567  2.49307161  1.80018949  1.59417603]]

 [[ 1.29835715  0.68233827  1.71073945  2.20933111  1.19207981]
  [ 1.92167189  1.81391779  0.80798328  2.92437809  0.12786959]
  [ 0.30180011  1.91668369  0.23808411 -0.66342146  0.80600902]]]

d_min = -0.9444454146364405  d_mean = 1.2252358772361591  d_max = 2.9243780949870155

f:
[[[ 75.  75.  25.  25.  75.]
  [ 25.   0.  75.  75.  75.]
  [ 25.  75.  75.  75.  75.]]

 [[ 75.  25.  75.  75.  25.]
  [ 75.  75.  25. 100.  25.]
  [ 25.  75.  25.  25.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [30]:
print("d:")
print(d)
print("f:")
print(f)

d:
[[[ 2.2116421   1.43129874  0.39223781  0.84893087  2.41528744]
  [ 0.94638992 -0.94444541  1.46646333  1.2486735   1.79732401]
  [-0.23001069  1.99802567  2.49307161  1.80018949  1.59417603]]

 [[ 1.29835715  0.68233827  1.71073945  2.20933111  1.19207981]
  [ 1.92167189  1.81391779  0.80798328  2.92437809  0.12786959]
  [ 0.30180011  1.91668369  0.23808411 -0.66342146  0.80600902]]]
f:
[[[ 75.  75.  25.  25.  75.]
  [ 25.   0.  75.  75.  75.]
  [ 25.  75.  75.  75.  75.]]

 [[ 75.  25.  75.  75.  25.]
  [ 75.  75.  25. 100.  25.]
  [ 25.  75.  25.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]